---
- name: Run Docker containers
  hosts: serveurs
  become: yes

  vars:
    app_path: /root/app
    app_port: 4567

  tasks:

    - name: Start containers
      ansible.builtin.shell: docker compose up -d
      args:
        chdir: "{{ app_path }}"

    - name: Wait for port to be open
      ansible.builtin.wait_for:
        host: localhost
        port: "{{ app_port }}"
        delay: 5
        timeout: 30

    - name: Verify HTTP availability
      ansible.builtin.uri:
        url: "http://localhost:{{ app_port }}"
        status_code: 200

